CREATE OR REPLACE PACKAGE EXCEPTION_PAC IS
    E_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT ( E_NULL, -1400 );
    E_FK EXCEPTION;
    PRAGMA EXCEPTION_INIT ( E_FK, -2291 );
END;

INSERT INTO CLIENTE VALUES (
    NULL,
    '214',
    '12314212',
    2,
    SYSDATE,
    14291091,
    ''
);

GRANT SELECT, INSERT ON SEGMERCADO TO USER_APP;

CREATE PUBLIC SYNONYM SEGMERCADO FOR USER_DEV.SEGMERCADO;

GRANT EXECUTE ON EXCEPTION_PAC TO PUBLIC;

CREATE PUBLIC SYNONYM EXCEPTION_PAC FOR USER_DEV.EXCEPTION_PAC;