CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE_PROC2 (
    P_ID                     IN   CLIENTE.ID%TYPE,
    P_RAZAO_SOCIAL           IN   CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ                   IN   CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO_ID          IN   CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO_PREVISTO   IN   CLIENTE.FATURAMENTO_PREVISTO%TYPE
) IS
BEGIN
    INSERT INTO CLIENTE (
        ID,
        RAZAO_SOCIAL,
        CNPJ,
        DATA_INCLUSAO,
        SEGMERCADO_ID,
        FATURAMENTO_PREVISTO
    ) VALUES (
        P_ID,
        P_RAZAO_SOCIAL,
        P_CNPJ,
        SYSDATE,
        P_SEGMERCADO_ID,
        P_FATURAMENTO_PREVISTO
    );

    COMMIT;
END;

EXECUTE INCLUIR_CLIENTE_PROC2(9,'supermercado ijk','67890',1,90000);

select * from cliente;
