SELECT C.NOME FROM TABELA_DE_CLIENTES c WHERE C.NOME LIKE '%Mattos';

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF INDENTIFICADOR, NOME CLIENTE FROM TABELA_DE_CLIENTES;

SELECT CPF AS INDENTIFICADOR, NOME AS CLIENTE FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS P WHERE P.CODIGO_DO_PRODUTO = '1000889';

SELECT * FROM TABELA_DE_PRODUTOS P WHERE P.SABOR = 'Uva';

SELECT * FROM TABELA_DE_PRODUTOS P WHERE P.SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS P WHERE P.EMBALAGEM = 'PET';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';

SELECT * FROM tabela_de_produtos WHERE PRECO_DE_LISTA > 19.50;

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA > 19.50;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS P WHERE P.SABOR = 'Laranja';

SELECT DISTINCT C.BAIRRO FROM TABELA_DE_CLIENTES C WHERE C.CIDADE = 'Rio de Janeiro';

SELECT * FROM NOTAS_FISCAIS NF WHERE ROWNUM <=10 AND NF.DATA_VENDA = TO_DATE('2017-01-01', 'YYYY-MM-DD');

SELECT * FROM TABELA_DE_CLIENTES P ORDER BY P.NOME ASC;

SELECT * FROM TABELA_DE_CLIENTES P ORDER BY P.NOME DESC;

SELECT * FROM TABELA_DE_PRODUTOS P WHERE P.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

SELECT * FROM ITENS_NOTAS_FISCAIS INF WHERE INF.codigo_do_produto = '1101035' AND INF.QUANTIDADE = 99;






