DECLARE
    V_SEGMERCADO_ID   CLIENTE.SEGMERCADO_ID%TYPE := 3;
    V_I               NUMBER(3);
BEGIN
    FOR V_I IN 1..6 LOOP
        ATUALIZAR_SEGMERCADO(V_I, V_SEGMERCADO_ID);
    END LOOP;
END;

SELECT
    *
FROM
    CLIENTE;