VARIABLE G_DESCRICAO VARCHAR2(100)

EXECUTE :G_DESCRICAO := OBTER_DESCRICAO_SEGMENTO(1);

PRINT G_DESCRICAO;

SET SERVEROUTPUT ON

DECLARE
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    V_DESCRICAO := OBTER_DESCRICAO_SEGMENTO(2);
    DBMS_OUTPUT.PUT_LINE('A Descrição do Segmento de Mercado é ' || V_DESCRICAO);
END;
