SET SERVEROUTPUT ON;
DECLARE
    CURSOR CUR_CLIENTE IS
    SELECT
        ID,
        RAZAO_SOCIAL
    FROM
        CLIENTE;

    V_ID             CLIENTE.ID%TYPE;
    V_RAZAO_SOCIAL   CLIENTE.RAZAO_SOCIAL%TYPE;
BEGIN
    OPEN CUR_CLIENTE;
    LOOP
        FETCH CUR_CLIENTE INTO
            V_ID,
            V_RAZAO_SOCIAL;
        EXIT WHEN CUR_CLIENTE%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID = ' || V_ID);
        DBMS_OUTPUT.PUT_LINE('Razão Social = ' || V_RAZAO_SOCIAL);
    END LOOP;
    CLOSE CUR_CLIENTE;
END;