SELECT
    *
FROM
    CLIENTE;

DECLARE
    CURSOR CUR_CLIENTE IS
    SELECT
        ID
    FROM
        CLIENTE;

    V_ID              CLIENTE.ID%TYPE;
    V_SEGMERCADO_ID   CLIENTE.SEGMERCADO_ID%TYPE := 2;
BEGIN
    OPEN CUR_CLIENTE;
    LOOP
        FETCH CUR_CLIENTE INTO V_ID;
        EXIT WHEN CUR_CLIENTE%NOTFOUND;
        ATUALIZAR_SEGMERCADO(P_SEGMERCADO_ID => V_SEGMERCADO_ID, P_ID => V_ID);
    END LOOP;

    CLOSE CUR_CLIENTE;
END;