SELECT
    *
FROM
    CLIENTE;

DECLARE
    CURSOR CUR_CLIENTE IS
    SELECT
        ID
    FROM
        CLIENTE;

    V_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 1;
BEGIN
    FOR CLI_REC IN CUR_CLIENTE LOOP
        ATUALIZAR_SEGMERCADO(P_SEGMERCADO_ID => V_SEGMERCADO_ID, P_ID => CLI_REC.ID);
    END LOOP;
END;