CREATE OR REPLACE FUNCTION OBTER_CATEGORIA (
    P_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
) RETURN CLIENTE.CATEGORIA%TYPE IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF P_FATURAMENTO_PREVISTO < 10000 THEN
        V_CATEGORIA := 'PEQUENO';
    ELSE
        IF P_FATURAMENTO_PREVISTO < 50000 THEN
            V_CATEGORIA := 'MEDIO';
        ELSE
            IF P_FATURAMENTO_PREVISTO < 100000 THEN
                V_CATEGORIA := 'MEDIO GRANDE';
            ELSE
                V_CATEGORIA := 'GRANDE';
            END IF;
        END IF;
    END IF;

    RETURN V_CATEGORIA;
END;