CREATE OR REPLACE PACKAGE CLIENTE_PAC IS
    PROCEDURE INCLUIR_CLIENTE (
        P_ID                     IN   CLIENTE.ID%TYPE,
        P_RAZAO_SOCIAL           IN   CLIENTE.RAZAO_SOCIAL%TYPE,
        P_CNPJ                   CLIENTE.CNPJ%TYPE,
        P_SEGMERCADO_ID          CLIENTE.SEGMERCADO_ID%TYPE,
        P_FATURAMENTO_PREVISTO   CLIENTE.FATURAMENTO_PREVISTO%TYPE
    );

END;

CREATE OR REPLACE PACKAGE BODY CLIENTE_PAC IS

    PROCEDURE INCLUIR_CLIENTE (
        P_ID                     IN   CLIENTE.ID%TYPE,
        P_RAZAO_SOCIAL           IN   CLIENTE.RAZAO_SOCIAL%TYPE,
        P_CNPJ                   CLIENTE.CNPJ%TYPE,
        P_SEGMERCADO_ID          CLIENTE.SEGMERCADO_ID%TYPE,
        P_FATURAMENTO_PREVISTO   CLIENTE.FATURAMENTO_PREVISTO%TYPE
    ) IS

        V_CATEGORIA           CLIENTE.CATEGORIA%TYPE;
        V_CNPJ                CLIENTE.CNPJ%TYPE := P_CNPJ;
        V_CODIGO_ERRO         NUMBER(5);
        V_MENSAGEM_ERRO       VARCHAR2(200);
        V_DUMMY               NUMBER;
        V_VERIFICA_SEGMENTO   BOOLEAN;
        E_SEGMENTO EXCEPTION;
    BEGIN
        V_VERIFICA_SEGMENTO := VERIFICA_SEGMENTO_MERCADO(P_SEGMERCADO_ID);
        IF V_VERIFICA_SEGMENTO = FALSE THEN
            RAISE E_SEGMENTO;
        END IF;
        V_CATEGORIA := OBTER_CATEGORIA_CLIENTE(P_FATURAMENTO_PREVISTO);
        FORMAT_CNPJ(V_CNPJ);
        INSERT INTO CLIENTE VALUES (
            P_ID,
            UPPER(P_RAZAO_SOCIAL),
            V_CNPJ,
            P_SEGMERCADO_ID,
            SYSDATE,
            P_FATURAMENTO_PREVISTO,
            V_CATEGORIA
        );

        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20010, 'Cliente já cadastrado');
        WHEN E_SEGMENTO THEN
            RAISE_APPLICATION_ERROR(-20011, 'Segmento de mercado inexistente');
        WHEN OTHERS THEN
            V_CODIGO_ERRO := SQLCODE;
            V_MENSAGEM_ERRO := SQLERRM;
            RAISE_APPLICATION_ERROR(-20000, TO_CHAR(V_CODIGO_ERRO)
                                            || V_MENSAGEM_ERRO);
    END;

END;

GRANT EXECUTE ON CLIENTE_PAC TO user_app;

CREATE PUBLIC SYNONYM CLIENTE_PAC FOR user_dev.cliente_pac;