CREATE OR REPLACE PROCEDURE INCLUIR_SEGMENTO (
    P_ID          IN   SEGMERCADO.ID%TYPE,
    P_DESCRICAO   IN   SEGMERCADO.DESCRICAO%TYPE
) IS
BEGIN
    INSERT INTO SEGMERCADO (
        ID,
        DESCRICAO
    ) VALUES (
        P_ID,
        P_DESCRICAO
    );

EXCEPTION
    WHEN EXCEPTION_PAC.E_NULL THEN
        RAISE_APPLICATION_ERROR(-20015, 'Campo Nulo! Por favor preecher.');
END;

